Home page route and layout
Davwidos/phone_catalog_project pull request #21
Opened 2024-05-22 11:16 UTC by weswojciech

2024-05-22 12:12 UTC, etuzimek commented on src/components/Homepage/Homepage.tsx
> +      <h1 className="main__title title">Welcome to Nice Gadgets store!</h1>
For some reason, the font weight is not working for h1

2024-05-22 12:13 UTC, etuzimek commented on src/components/Shop-by-category/Shop-by-category.tsx
> +      <h1 className="shop-by-category__title">Shop by category</h1>
For some reason, the font weight is not working for h1

2024-05-22 12:16 UTC, etuzimek requested changes
Font-weight problems

2024-05-23 10:18 UTC, Davwidos approved these changes

2024-05-23 10:24 UTC, etuzimek approved these changes

2024-05-23 10:25 UTC, merged